version: '2'

services: 
  entry: 
    build:
      context: ./kiwi-entry
      dockerfile: entry.dockerfile
    ports:
      - "8080:8000"
    networks:
      - user-network
      - service-network

  user: 
    build: 
      context: ./kiwi-user-manager
      dockerfile: user.dockerfile
    ports:
      - "80"
    networks:
      - user-network

  engine:
    build:
      context: ./kiwi-engine-selector
      dockerfile: engine.dockerfile
    ports: 
      - "8000"
    networks:
      - service-network
      - content-network
    restart: always

  content:
    build:
      context: ./kiwi-content-crawler
      dockerfile: content.dockerfile
    ports:
      - "5000"
    networks:
      - service-network
      - content-network
    restart: always

  random:
    build:
      context: ./kiwi-random
      dockerfile: service.dockerfile
    ports:
      - "8000"
    networks:
      - random-network
      - service-network
    restart: always

  webapp:
    build:
      context: ./kiwi-mobile-frontend
      dockerfile: webapp.dockerfile
    networks:
      - webapp-network
    ports:
      - "80"
    expose:
      - "80"
  
networks:
  random-network:
    driver: bridge
  service-network:
    driver: bridge
  content-network:
    driver: bridge
  user-network:
    driver: bridge
  webapp-network:
    driver: bridge
