version: '2'

services: 
  random:
    build:
      context: .
      dockerfile: service.dockerfile
    ports:
      - "8000:8000"
    networks:
      - random-network
  
  mysqldb:
    build:
      context: .
      dockerfile: mysql.dockerfile
    networks:
      - random-network
    ports:
      - "3306"

networks:
  random-network:
    driver: bridge
